#spring:
  #application:
    #name: eureka-auth
  #config:
    #import: "optional:configserver:http://configserver:8888"
    #import: "optional:configserver:http://configserver:8888"

spring:
  profiles:
    include: oauth
